### ISSUE TITLE
Physikalische Daten

### ISSUE THREAD

**Issue by jotron** [jotron/Simulation#2]
Um ein Sonnensystem ähnliches Programm zu schreiben brauchen wir von jedem Planeten:
- MASSE
- RADIUS
- DISTANZ zur Sonne mit zugehöriger GESCHWINDIGKEIT (also z.b V-Aphel und R-Aphel)

Schreibt die Antwort einfach in den Kommentar

**Comment by pyupi** [comment]
D = Distanz zur Sonne
Sonne: R = 696.342 km
            M = 2 * 10**30 kg
            V = 0

Erde: D-Aphel = 152,1 Mio km
         R = 6378,16 km
         M = 5,974 * 10**24 kg
         V-Aphel = 29,29 km/s
Mars: D-Aphel = 249,9 Mio km
          R = 3396,2 km
          M = 6.419 * 10**23 kg
          V-Aphel = 21,97 km/s
Jupiter: D-Aphel = 819 Mio km
             R = 71492 km
             M = 1.9 * 10**27 kg
             V-Aphel = 17.17 km/s
Saturn: D-Aphel = 1518.57 km
            R = 60268 km
            M = 5,685 * 10**26
            V-Aphel = 12.78 km/s

**Comment by jotron** [comment]
https://nssdc.gsfc.nasa.gov/planetary/factsheet/jupiterfact.html
https://nssdc.gsfc.nasa.gov/planetary/factsheet/saturnfact.html

Bezüglich üserer Simulation und de Nasa chönnt die dine Date für Geschwindigkeit von Jupiter und Saturn ned stimme 🙃

**Comment by pyupi** [comment]
Okey denn nimmsch demfall eif die date

**Comment by pyupi** [comment]
kleine Korrektur:
Jupiter:
V-Aphel = 12.45km/s

Saturn:
V-Aphel = 9.11km/s
