### ISSUE TITLE
Bericht: Arbeitsaufteilung auflisten

### ISSUE THREAD

**Issue by jotron** [jotron/Simulation#3]

**Comment by pyupi** [comment]
Simon:
Kapitel Ziel im Bericht, Formel für  Acceleration Vektor
Joel:
Erste Teile des Programmcodes für unser Planetensystem
Amin:
Runge Kutta Verfahren & Startmenu programmiert

**Comment by pyupi** [comment]
Simon:
Berechnen und finden der Startdaten

**Comment by pyupi** [comment]
Amin:
Startmenu
